day16/config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do

    member do
      post :create_comment
    end
  end
  resources :foods

  root 'welcome#index'

end

day16/app/helpers/application_helper.rb
module ApplicationHelper
end

day16/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

day16/app/helpers/welcome_helper.rb
module WelcomeHelper
end

day16/app/views/layouts/_navbar.html.haml
%ul.nav.navbar-nav
  %li.active
    = link_to "Home", root_path
  %li
    %a{:href => "#about"} About
  %li
    %a{:href => "#contact"} Contact
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      Dropdown
      %b.caret
    %ul.dropdown-menu
      %li
        %a{:href => "#"} Action
      %li
        %a{:href => "#"} Another action
      %li
        %a{:href => "#"} Something else here
      %li.divider
      %li.dropdown-header Nav header
      %li
        %a{:href => "#"} Separated link
      %li
        %a{:href => "#"} One more separated link
%ul.nav.navbar-nav.navbar-right
  %li
    %a{:href => "#"} Logout
  %li
    %a{:href => "#"} Register
  %li
    %a{:href => "#"} Login

day16/app/views/restaurants/_form.html.haml
= form_for(@restaurant) do |f|
  - if @restaurant.errors.any?
    - @restaurant.errors.full_messages.each do |message|
      = message
      %br
  .field
    = f.label :name
    %br
      = f.text_field :name
  .field
    = f.label :description
    %br
      = f.text_area :description
  .field
    = f.label :address
    %br
      = f.text_field :address
  .field
    = f.label :city
    %br
      = f.text_field :city
  .field
    = f.label :state
    %br
      = f.text_field :state
  .field
    = f.label :zip
    %br
      = f.text_field :zip
  .field
    = f.label :owner
    %br
      = f.text_field :owner
  .field
    = f.label :opening
    %br
      = f.date_field :opening
  .field
    = hidden_field_tag 'restaurant[food_ids][]', ''
    - @foods.each do |food|
      = check_box_tag 'restaurant[food_ids][]', food.id, @restaurant.foods.include?(food)
      = food.name
      %br
  .actions
    = f.submit

day16/app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Restaurants</h1>

<% @restaurants.each do |restaurant| %>
    ||||||||||||
    <%= restaurant.is_open? %>
    ||||||||||||
    <%= restaurant.name %>
    <%= restaurant.description %>
    <%= restaurant.address %>
    <%= restaurant.city %>
    <%= restaurant.state %>
    <%= restaurant.zip %>
    <%= restaurant.owner %>
    <%= restaurant.opening %>
    <%= link_to 'Show', restaurant_path(restaurant) %>
    <%= link_to 'Edit', edit_restaurant_path(restaurant) %>
    <%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %>
    <br>
<% end %>

<br>

day16/app/views/welcome/index.html.haml
%h1.hello_world.end_of_the_world#this_is_an_id{ class: "#{@new_class}" }
  Foooooood
  is good
  %small
    is awesome
down here
%span{ class: "glyphicon glyphicon-search" }
= Rails.root
%span.glyphicon.glyphicon-phone
%span.glyphicon.glyphicon-menu-down
%div
  This is some cool text.

%br

- if @array.length > 3
  Good morning
  %strong sunshine.

- @array.each do |arr|
  = arr.inspect


%a.btn.btn-success
  Robbi's Link

%div.col-md-4
  %img{ src: "/assets/magic.gif" }
  = image_tag "magic.gif", class: "img-circle"
  = image_tag "funny_images/sup_foo.jpg"

%div.row
  %div.col-md-4.col-md-offset-2
    Hello 1
  %div.col-md-4
    Hello 2
  %div.col-md-5.col-md-offset-1
    Hello 3
  %div.col-md-6
    Hello 4



.jumbotron
  %h1 Hello, world!
  %p This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.
  %p
    %a.btn.btn-primary.btn-lg{:href => "#", :role => "button"} Learn more &raquo;
.page-header
  %h1 Buttons
%p
  %button.btn.btn-lg.btn-default{:type => "button"} Default
  %button.btn.btn-lg.btn-primary{:type => "button"} Primary
  %button.btn.btn-lg.btn-success{:type => "button"} Success
  %button.btn.btn-lg.btn-info{:type => "button"} Info
  %button.btn.btn-lg.btn-warning{:type => "button"} Warning
  %button.btn.btn-lg.btn-danger{:type => "button"} Danger
  %button.btn.btn-lg.btn-link{:type => "button"} Link
%p
  %button.btn.btn-default{:type => "button"} Default
  %button.btn.btn-primary{:type => "button"} Primary
  %button.btn.btn-success{:type => "button"} Success
  %button.btn.btn-info{:type => "button"} Info
  %button.btn.btn-warning{:type => "button"} Warning
  %button.btn.btn-danger{:type => "button"} Danger
  %button.btn.btn-link{:type => "button"} Link
%p
  %button.btn.btn-sm.btn-default{:type => "button"} Default
  %button.btn.btn-sm.btn-primary{:type => "button"} Primary
  %button.btn.btn-sm.btn-success{:type => "button"} Success
  %button.btn.btn-sm.btn-info{:type => "button"} Info
  %button.btn.btn-sm.btn-warning{:type => "button"} Warning
  %button.btn.btn-sm.btn-danger{:type => "button"} Danger
  %button.btn.btn-sm.btn-link{:type => "button"} Link
%p
  %button.btn.btn-xs.btn-default{:type => "button"} Default
  %button.btn.btn-xs.btn-primary{:type => "button"} Primary
  %button.btn.btn-xs.btn-success{:type => "button"} Success
  %button.btn.btn-xs.btn-info{:type => "button"} Info
  %button.btn.btn-xs.btn-warning{:type => "button"} Warning
  %button.btn.btn-xs.btn-danger{:type => "button"} Danger
  %button.btn.btn-xs.btn-link{:type => "button"} Link
.page-header
  %h1 Thumbnails
%img.img-thumbnail{:alt => "A generic square placeholder image with a white border around it, making it resemble a photograph taken with an old instant camera", "data-src" => "holder.js/200x200"}
  .page-header
    %h1 Dropdown menus
  .dropdown.theme-dropdown.clearfix
    %a#dropdownMenu1.sr-only.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :role => "button"}
      Dropdown
      %b.caret
    %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1", :role => "menu"}
      %li.active{:role => "presentation"}
        %a{:href => "#", :role => "menuitem", :tabindex => "-1"} Action
      %li{:role => "presentation"}
        %a{:href => "#", :role => "menuitem", :tabindex => "-1"} Another action
      %li{:role => "presentation"}
        %a{:href => "#", :role => "menuitem", :tabindex => "-1"} Something else here
      %li.divider{:role => "presentation"}
      %li{:role => "presentation"}
        %a{:href => "#", :role => "menuitem", :tabindex => "-1"} Separated link
  .page-header
    %h1 Navbars
  .navbar.navbar-default
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "#"} Project name
      .navbar-collapse.collapse
        %ul.nav.navbar-nav
          %li.active
            %a{:href => "#"} Home
          %li
            %a{:href => "#about"} About
          %li
            %a{:href => "#contact"} Contact
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Dropdown
              %b.caret
            %ul.dropdown-menu
              %li
                %a{:href => "#"} Action
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider
              %li.dropdown-header Nav header
              %li
                %a{:href => "#"} Separated link
              %li
                %a{:href => "#"} One more separated link
      / /.nav-collapse
  .navbar.navbar-inverse
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "#"} Project name
      .navbar-collapse.collapse
        %ul.nav.navbar-nav
          %li.active
            %a{:href => "#"} Home
          %li
            %a{:href => "#about"} About
          %li
            %a{:href => "#contact"} Contact
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Dropdown
              %b.caret
            %ul.dropdown-menu
              %li
                %a{:href => "#"} Action
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider
              %li.dropdown-header Nav header
              %li
                %a{:href => "#"} Separated link
              %li
                %a{:href => "#"} One more separated link
      / /.nav-collapse
  .page-header
    %h1 Alerts
  .alert.alert-success
    %strong Well done!
    You successfully read this important alert message.
  .alert.alert-info
    %strong Heads up!
    This alert needs your attention, but it's not super important.
  .alert.alert-warning
    %strong Warning!
    Best check yo self, you're not looking too good.
  .alert.alert-danger
    %strong Oh snap!
    Change a few things up and try submitting again.
  .page-header
    %h1 Progress bars
  .progress
    .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "60", :role => "progressbar", :style => "width: 60%;"}
      %span.sr-only 60% Complete
  .progress
    .progress-bar.progress-bar-success{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "40", :role => "progressbar", :style => "width: 40%"}
      %span.sr-only 40% Complete (success)
  .progress
    .progress-bar.progress-bar-info{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "20", :role => "progressbar", :style => "width: 20%"}
      %span.sr-only 20% Complete
  .progress
    .progress-bar.progress-bar-warning{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "60", :role => "progressbar", :style => "width: 60%"}
      %span.sr-only 60% Complete (warning)
  .progress
    .progress-bar.progress-bar-danger{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "80", :role => "progressbar", :style => "width: 80%"}
      %span.sr-only 80% Complete (danger)
  .progress
    .progress-bar.progress-bar-success{:style => "width: 35%"}
      %span.sr-only 35% Complete (success)
    .progress-bar.progress-bar-warning{:style => "width: 20%"}
      %span.sr-only 20% Complete (warning)
    .progress-bar.progress-bar-danger{:style => "width: 10%"}
      %span.sr-only 10% Complete (danger)
  .page-header
    %h1 List groups
  .row
    .col-sm-4
      %ul.list-group
        %li.list-group-item Cras justo odio
        %li.list-group-item Dapibus ac facilisis in
        %li.list-group-item Morbi leo risus
        %li.list-group-item Porta ac consectetur ac
        %li.list-group-item Vestibulum at eros
    / /.col-sm-4
    .col-sm-4
      .list-group
        %a.list-group-item.active{:href => "#"}
          Cras justo odio
        %a.list-group-item{:href => "#"} Dapibus ac facilisis in
        %a.list-group-item{:href => "#"} Morbi leo risus
        %a.list-group-item{:href => "#"} Porta ac consectetur ac
        %a.list-group-item{:href => "#"} Vestibulum at eros
    / /.col-sm-4
    .col-sm-4
      .list-group
        %a.list-group-item.active{:href => "#"}
          %h4.list-group-item-heading List group item heading
          %p.list-group-item-text Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.
        %a.list-group-item{:href => "#"}
          %h4.list-group-item-heading List group item heading
          %p.list-group-item-text Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.
        %a.list-group-item{:href => "#"}
          %h4.list-group-item-heading List group item heading
          %p.list-group-item-text Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.
    / /.col-sm-4
  .page-header
    %h1 Panels
  .row
    .col-sm-4
      .panel.panel-default
        .panel-heading
          %h3.panel-title Panel title
        .panel-body
          Panel content
      .panel.panel-primary
        .panel-heading
          %h3.panel-title Panel title
        .panel-body
          Panel content
    / /.col-sm-4
    .col-sm-4
      .panel.panel-success
        .panel-heading
          %h3.panel-title Panel title
        .panel-body
          Panel content
      .panel.panel-info
        .panel-heading
          %h3.panel-title Panel title
        .panel-body
          Panel content
    / /.col-sm-4
    .col-sm-4
      .panel.panel-warning
        .panel-heading
          %h3.panel-title Panel title
        .panel-body
          Panel content
      .panel.panel-danger
        .panel-heading
          %h3.panel-title Panel title
        .panel-body
          Panel content
    / /.col-sm-4
  .page-header
    %h1 Wells
  .well
    %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed diam eget risus varius blandit sit amet non magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras mattis consectetur purus sit amet fermentum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur.