day17/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do

    member do
      post :create_comment
    end
  end
  resources :foods

  root 'welcome#index'

end

day17/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

day17/app/models/food.rb
# Fat Models, Skinny Controllers
class Food < ActiveRecord::Base
  # restaurant_id - integer
  # belongs_to :restaurant
  has_many :restaurant_foods
  has_many :restaurants, through: :restaurant_foods
  # @food.restaurants

  has_many :comments, as: :commentable

  EXPIRED_OPTIONS = [
    ["True", true],
    ["False", false]
  ]

end

day17/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true

  # has_many :foods, dependent: :destroy
  has_many :restaurant_foods
  has_many :foods, through: :restaurant_foods

  has_many :comments, as: :commentable

  def is_open?
    # if the created_at date is <= todays date
    #   then the restaurant is open
    # otherwise
    #   the restaurant is closed
    if self.opening && self.opening <= Date.today
      "Open"
    else
      "Closed"
    end
  end
end

day17/app/models/restaurant_food.rb
class RestaurantFood < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :food
end

day17/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

day17/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

day17/app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
    @restaurants = Restaurant.all
  end

  def create
    @food = Food.create food_params
    redirect_to foods_path
  end

  def edit
    @food = Food.find params[:id]
    @restaurants = Restaurant.all
  end

  def update
    @food = Food.find params[:id]
    @food.update_attributes food_params
    redirect_to foods_path
  end

  def destroy
    @food = Food.find params[:id]
    @food.delete
    redirect_to foods_path
  end

  private 

  def food_params
    params.require(:food).permit(
      :name,
      :description,
      :flavor,
      :expired,
      :texture,
      :cost,
      restaurant_ids: []
    )
  end
end

day17/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @foods = @restaurant.foods
    @comment = Comment.new
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
    @foods = Food.all
  end

  def create_comment
    @restaurant = Restaurant.find params[:id]
    @comment = @restaurant.comments.create comment_params
    redirect_to restaurant_path(@restaurant)
  end

  # GET /restaurants/1/edit
  def edit
    @foods = Food.all
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @foods = Food.all
    # flash
    if @restaurant.save
      flash[:notice] = 'Restaurant was successfully created.'
      redirect_to restaurants_path
    else
      flash[:error] = "Restaurant was NOT saved."
      render :new
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    @foods = Food.all
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(
        :name,
        :description,
        :address,
        :city,
        :state,
        :zip,
        :owner,
        :opening,
        food_ids: []
      )
    end

    def comment_params
      params.require(:comment).permit(
        :content
      )
    end
end

day17/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
    @array = [1,2,3,4,5,6]
    @new_class = "dudeman"
  end
end

day17/app/helpers/application_helper.rb
module ApplicationHelper
  def active_link(current_link)
    # puts params.inspect
    # params[:controller] == link_controller ? 'active' : ''
    :active if params[:controller] == current_link
  end

end

day17/app/helpers/foods_helper.rb
module FoodsHelper
end

day17/app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def is_restaurant_open?(restaurant_object)
    restaurant_object.is_open?.downcase
  end
end

day17/app/helpers/welcome_helper.rb
module WelcomeHelper
  def shia_magic
    content_tag(:div,
      image_tag("magic.gif") + 
      image_tag("magic.gif", class: "img-circle") + 
      image_tag("funny_images/sup_foo.jpg"),
      class: "col-md-4"
    )
  end
end

day17/app/views/foods/_form.html.erb
<br>
<%= @food.inspect %>
<br>
<%= form_for [@food] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :flavor %>
  <%= f.text_field :flavor %>
  <br>
  <%= f.label :expired %>
  <%= f.select :expired, options_for_select(Food::EXPIRED_OPTIONS, f.object.expired), include_blank: "--- Select ---" %>
<!--   <select name="food[expired]">
    <option value="true">True</option>
    <option>False</option>
  </select>
 -->
  <br>
  <%= f.label :texture %>
  <%= f.text_field :texture %>
  <br>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <br>
  <% @restaurants.each do |restaurant| %>
    <%= check_box_tag 'food[restaurant_ids][]', restaurant.id, @food.restaurants.include?(restaurant) %>
    <%= restaurant.name %>
    <br>
  <% end %>

  <%= f.submit %>
  |
  <%= link_to "Cancel", foods_path %>
<% end %>

day17/app/views/foods/_sidebar.html.haml
%li
  = link_to 'New Food', new_food_path

day17/app/views/foods/edit.html.erb
<h3>Edit Food</h3>

<%= render 'form' %>

day17/app/views/foods/index.html.erb
<h3>Food List</h3>
<ul>
<% @foods.each do |food| %>
  <li>
    <%= food.name %>
    <%= food.description %>
    <%= link_to "Edit", edit_food_path(food) %>
    |
    <%= link_to "Delete", food_path(food), method: :delete %>
  </li>
<% end %>
</ul>

day17/app/views/foods/new.html.erb
<h3>New Food</h3>

<%= render 'form' %>

day17/app/views/layouts/_navbar.html.haml
%ul.nav.navbar-nav
  %li{class: active_link('welcome')}
    / <li class="">
    = link_to "Home", root_path
  %li{class: active_link('restaurants')}
    = link_to "Restaurants", restaurants_path
  %li{class: active_link('foods')}
    = link_to "Foods", foods_path
  / %li.dropdown
  /   %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
  /     Dropdown
  /     %b.caret
  /   %ul.dropdown-menu
  /     %li
  /       %a{:href => "#"} Action
  /     %li
  /       %a{:href => "#"} Another action
  /     %li
  /       %a{:href => "#"} Something else here
  /     %li.divider
  /     %li.dropdown-header Nav header
  /     %li
  /       %a{:href => "#"} Separated link
  /     %li
  /       %a{:href => "#"} One more separated link
%ul.nav.navbar-nav.navbar-right
  - if current_user
    %li
      = link_to "Logout #{current_user.email}", destroy_user_session_path, method: :delete
  - else
    %li
      = link_to 'Register', new_user_registration_path
    %li
      = link_to 'Login', new_user_session_path

day17/app/views/layouts/_sidebar.html.haml
%h1= params[:controller].capitalize
= params.inspect
%ul
  %li
    = link_to "Home Page", root_path
  = render 'sidebar'

day17/app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    / %link{:href => "../../assets/ico/favicon.ico", :rel => "shortcut icon"}
    %title Rails Application
    / Bootstrap core CSS
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    / Just for debugging purposes. Don't actually copy this line!
    /[if lt IE 9] <script src="../../assets/js/ie8-responsive-file-warning.js"></script>
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  %body{:role => "document"}
    / Fixed navbar
    .navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Rails Application", root_path, class: "navbar-brand"
        .navbar-collapse.collapse
          = render 'layouts/navbar'
        / /.nav-collapse
    .container.theme-showcase{:role => "main"}
      %div.row
        %div.col-md-3
          = render 'layouts/sidebar'
        %div.col-md-9
          - if notice || alert
            %p.notice= notice
            %p.alert= alert
          = yield

day17/app/views/restaurants/_form.html.haml
= form_for(@restaurant) do |f|
  - if @restaurant.errors.any?
    - @restaurant.errors.full_messages.each do |message|
      = message
      %br
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :description
    = f.text_area :description, class: "form-control"
  .form-group
    = f.label :address
    = f.text_field :address, class: "form-control"
  .form-group
    = f.label :city
    = f.text_field :city, class: "form-control"
  .form-group
    = f.label :state
    = f.text_field :state, class: "form-control"
  .form-group
    = f.label :zip
    = f.text_field :zip, class: "form-control"
  .form-group
    = f.label :owner
    = f.text_field :owner, class: "form-control"
  .form-group
    = f.label :opening
    = f.date_field :opening, class: "form-control"
  .checkbox
    = hidden_field_tag 'restaurant[food_ids][]', ''
    - @foods.each do |food|
      %label 
        = check_box_tag 'restaurant[food_ids][]', food.id, @restaurant.foods.include?(food)
        = food.name
  = f.submit "Submit", class: "btn btn-primary"

day17/app/views/restaurants/_sidebar.html.haml
%li
  = link_to 'New Restaurant', new_restaurant_path

day17/app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

day17/app/views/restaurants/index.html.haml
%p#notice= notice
%h1 Listing Restaurants
%ul
  - @restaurants.each do |restaurant|
    %li.johnsclass{ class: is_restaurant_open?(restaurant)}
      ||||||||||||
      = restaurant.is_open?
      ||||||||||||
      = restaurant.name
      = restaurant.description
      = restaurant.address
      = restaurant.city
      = restaurant.state
      = restaurant.zip
      = restaurant.owner
      = restaurant.opening
      = link_to 'Show', restaurant_path(restaurant)
      = link_to 'Edit', edit_restaurant_path(restaurant)
      = link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }
%br

day17/app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

day17/app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @restaurant.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @restaurant.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @restaurant.zip %>
</p>

<p>
  <strong>Food List:</strong>
  <%= link_to "Add Food", edit_restaurant_path(@restaurant) %>
  <ul>
    <% @foods.each do |food| %>
      <li><%= food.name %> <%= food.description %> <%= food.cost %></li>
    <% end %>
  </ul>
</p>
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>
<br>
<% @restaurant.comments.each do |comment| %>
  <%= comment.content %>
  <br>
<% end %>

<%= form_for @comment, url: create_comment_restaurant_path(@restaurant) do |f| %>
  <!-- create_comment_restaurant -->
  <%= f.label :content %>
  <%= f.text_area :content %>
  <br>
  <%= f.submit %>
<% end %>

day17/app/views/welcome/_sidebar.html.haml
%li
  = link_to "Restaurant List", restaurants_path
%li
  = link_to "Food List", foods_path

day17/app/views/welcome/index.html.haml
%h1.hello_world.end_of_the_world#this_is_an_id{ class: "#{@new_class}" }
  Foooooood
  is good
  %small
    is awesome
down here
%span{ class: "glyphicon glyphicon-search" }
= Rails.root
%span.glyphicon.glyphicon-phone
%span.glyphicon.glyphicon-menu-down
%div
  This is some cool text.

%br

- if @array.length > 3
  Good morning
  %strong sunshine.

- @array.each do |arr|
  = arr.inspect


%a.btn.btn-success
  Robbi's Link

= shia_magic

%div.row
  %div.col-md-4.col-md-offset-2
    Hello 1
  %div.col-md-4
    Hello 2
  %div.col-md-5.col-md-offset-1
    Hello 3
  %div.col-md-6
    Hello 4



.jumbotron
  %h1 Hello, world!
  %p This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.
  %p
    %a.btn.btn-primary.btn-lg{:href => "#", :role => "button"} Learn more &raquo;
.page-header
  %h1 Buttons
%p
  %button.btn.btn-lg.btn-default{:type => "button"} Default
  %button.btn.btn-lg.btn-primary{:type => "button"} Primary
  %button.btn.btn-lg.btn-success{:type => "button"} Success
  %button.btn.btn-lg.btn-info{:type => "button"} Info
  %button.btn.btn-lg.btn-warning{:type => "button"} Warning
  %button.btn.btn-lg.btn-danger{:type => "button"} Danger
  %button.btn.btn-lg.btn-link{:type => "button"} Link
%p
  %button.btn.btn-default{:type => "button"} Default
  %button.btn.btn-primary{:type => "button"} Primary
  %button.btn.btn-success{:type => "button"} Success
  %button.btn.btn-info{:type => "button"} Info
  %button.btn.btn-warning{:type => "button"} Warning
  %button.btn.btn-danger{:type => "button"} Danger
  %button.btn.btn-link{:type => "button"} Link
%p
  %button.btn.btn-sm.btn-default{:type => "button"} Default
  %button.btn.btn-sm.btn-primary{:type => "button"} Primary
  %button.btn.btn-sm.btn-success{:type => "button"} Success
  %button.btn.btn-sm.btn-info{:type => "button"} Info
  %button.btn.btn-sm.btn-warning{:type => "button"} Warning
  %button.btn.btn-sm.btn-danger{:type => "button"} Danger
  %button.btn.btn-sm.btn-link{:type => "button"} Link
%p
  %button.btn.btn-xs.btn-default{:type => "button"} Default
  %button.btn.btn-xs.btn-primary{:type => "button"} Primary
  %button.btn.btn-xs.btn-success{:type => "button"} Success
  %button.btn.btn-xs.btn-info{:type => "button"} Info
  %button.btn.btn-xs.btn-warning{:type => "button"} Warning
  %button.btn.btn-xs.btn-danger{:type => "button"} Danger
  %button.btn.btn-xs.btn-link{:type => "button"} Link
.page-header
  %h1 Thumbnails
%img.img-thumbnail{:alt => "A generic square placeholder image with a white border around it, making it resemble a photograph taken with an old instant camera", "data-src" => "holder.js/200x200"}
  .page-header
    %h1 Dropdown menus
  .dropdown.theme-dropdown.clearfix
    %a#dropdownMenu1.sr-only.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :role => "button"}
      Dropdown
      %b.caret
    %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1", :role => "menu"}
      %li.active{:role => "presentation"}
        %a{:href => "#", :role => "menuitem", :tabindex => "-1"} Action
      %li{:role => "presentation"}
        %a{:href => "#", :role => "menuitem", :tabindex => "-1"} Another action
      %li{:role => "presentation"}
        %a{:href => "#", :role => "menuitem", :tabindex => "-1"} Something else here
      %li.divider{:role => "presentation"}
      %li{:role => "presentation"}
        %a{:href => "#", :role => "menuitem", :tabindex => "-1"} Separated link
  .page-header
    %h1 Navbars
  .navbar.navbar-default
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "#"} Project name
      .navbar-collapse.collapse
        %ul.nav.navbar-nav
          %li.active
            %a{:href => "#"} Home
          %li
            %a{:href => "#about"} About
          %li
            %a{:href => "#contact"} Contact
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Dropdown
              %b.caret
            %ul.dropdown-menu
              %li
                %a{:href => "#"} Action
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider
              %li.dropdown-header Nav header
              %li
                %a{:href => "#"} Separated link
              %li
                %a{:href => "#"} One more separated link
      / /.nav-collapse
  .navbar.navbar-inverse
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "#"} Project name
      .navbar-collapse.collapse
        %ul.nav.navbar-nav
          %li.active
            %a{:href => "#"} Home
          %li
            %a{:href => "#about"} About
          %li
            %a{:href => "#contact"} Contact
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Dropdown
              %b.caret
            %ul.dropdown-menu
              %li
                %a{:href => "#"} Action
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider
              %li.dropdown-header Nav header
              %li
                %a{:href => "#"} Separated link
              %li
                %a{:href => "#"} One more separated link
      / /.nav-collapse
  .page-header
    %h1 Alerts
  .alert.alert-success
    %strong Well done!
    You successfully read this important alert message.
  .alert.alert-info
    %strong Heads up!
    This alert needs your attention, but it's not super important.
  .alert.alert-warning
    %strong Warning!
    Best check yo self, you're not looking too good.
  .alert.alert-danger
    %strong Oh snap!
    Change a few things up and try submitting again.
  .page-header
    %h1 Progress bars
  .progress
    .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "60", :role => "progressbar", :style => "width: 60%;"}
      %span.sr-only 60% Complete
  .progress
    .progress-bar.progress-bar-success{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "40", :role => "progressbar", :style => "width: 40%"}
      %span.sr-only 40% Complete (success)
  .progress
    .progress-bar.progress-bar-info{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "20", :role => "progressbar", :style => "width: 20%"}
      %span.sr-only 20% Complete
  .progress
    .progress-bar.progress-bar-warning{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "60", :role => "progressbar", :style => "width: 60%"}
      %span.sr-only 60% Complete (warning)
  .progress
    .progress-bar.progress-bar-danger{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "80", :role => "progressbar", :style => "width: 80%"}
      %span.sr-only 80% Complete (danger)
  .progress
    .progress-bar.progress-bar-success{:style => "width: 35%"}
      %span.sr-only 35% Complete (success)
    .progress-bar.progress-bar-warning{:style => "width: 20%"}
      %span.sr-only 20% Complete (warning)
    .progress-bar.progress-bar-danger{:style => "width: 10%"}
      %span.sr-only 10% Complete (danger)
  .page-header
    %h1 List groups
  .row
    .col-sm-4
      %ul.list-group
        %li.list-group-item Cras justo odio
        %li.list-group-item Dapibus ac facilisis in
        %li.list-group-item Morbi leo risus
        %li.list-group-item Porta ac consectetur ac
        %li.list-group-item Vestibulum at eros
    / /.col-sm-4
    .col-sm-4
      .list-group
        %a.list-group-item.active{:href => "#"}
          Cras justo odio
        %a.list-group-item{:href => "#"} Dapibus ac facilisis in
        %a.list-group-item{:href => "#"} Morbi leo risus
        %a.list-group-item{:href => "#"} Porta ac consectetur ac
        %a.list-group-item{:href => "#"} Vestibulum at eros
    / /.col-sm-4
    .col-sm-4
      .list-group
        %a.list-group-item.active{:href => "#"}
          %h4.list-group-item-heading List group item heading
          %p.list-group-item-text Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.
        %a.list-group-item{:href => "#"}
          %h4.list-group-item-heading List group item heading
          %p.list-group-item-text Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.
        %a.list-group-item{:href => "#"}
          %h4.list-group-item-heading List group item heading
          %p.list-group-item-text Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.
    / /.col-sm-4
  .page-header
    %h1 Panels
  .row
    .col-sm-4
      .panel.panel-default
        .panel-heading
          %h3.panel-title Panel title
        .panel-body
          Panel content
      .panel.panel-primary
        .panel-heading
          %h3.panel-title Panel title
        .panel-body
          Panel content
    / /.col-sm-4
    .col-sm-4
      .panel.panel-success
        .panel-heading
          %h3.panel-title Panel title
        .panel-body
          Panel content
      .panel.panel-info
        .panel-heading
          %h3.panel-title Panel title
        .panel-body
          Panel content
    / /.col-sm-4
    .col-sm-4
      .panel.panel-warning
        .panel-heading
          %h3.panel-title Panel title
        .panel-body
          Panel content
      .panel.panel-danger
        .panel-heading
          %h3.panel-title Panel title
        .panel-body
          Panel content
    / /.col-sm-4
  .page-header
    %h1 Wells
  .well
    %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed diam eget risus varius blandit sit amet non magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras mattis consectetur purus sit amet fermentum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur.